project_id = "xzswyicqxtocruvjyqlf"

[functions.submit-vote]
verify_jwt = false

[functions.detect-winner]
verify_jwt = false

[functions.process-claim]
verify_jwt = false

[functions.refill-payout]
verify_jwt = false

[functions.admin]
verify_jwt = false

[functions.verify-token-balance]
verify_jwt = false


[functions.onchain-data]
verify_jwt = false

[functions.ifttt-webhook]
verify_jwt = false

[functions.auth-register]
verify_jwt = false